### ISSUE TITLE
Is there a way to add rotation

### ISSUE THREAD

**Issue by ngehlert** [madox2/react-tagcloud#11]
Is there a possibility to add some sort of rotation, so it looks something like this?
https://altoona.psu.edu/sites/default/files/styles/photo_gallery_large/http/news.psu.edu/sites/default/files/success-word-cloud.jpg?itok=4_HTmhRg+
![Demo Image](https://altoona.psu.edu/sites/default/files/styles/photo_gallery_large/http/news.psu.edu/sites/default/files/success-word-cloud.jpg?itok=4_HTmhRg+)

**Comment by madox2** [comment]
Hi, it is currently not possible. I doubt that it will possible in the future since I want this library to remain very lightweight. However any contributions are welcome
