### ISSUE TITLE
Incompatible with Internet Explorer

### ISSUE THREAD

**Issue by hbertelli** [madox2/react-tagcloud#2]
The method Object.assign used on TagCloud.js as part of the "const omittedProps" is incompatible with Internet Explorer according to MDN (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign)

The error that I got on IE is: SCRIPT438: Object doesn't support property or method 'assign'. tag-cloud.js (33,5)

Could you please check that? Thank you!

**Comment by madox2** [comment]
Thanks for reporting this issue. It is fixed in [v0.4.1](/madox2/react-tagcloud/releases/tag/v0.4.1) release.
