### ISSUE TITLE
Mouse hover event

### ISSUE THREAD

**Issue by moona3k** [madox2/react-tagcloud#24]
Request - Add `onMouseOver` and `onMouseOut` events

Sample API
`const onMouseOver = tag => console.log("this is value and count", tag.value, tag.count)`

`<TagCloud onMouseOver={onMouseOver} onMouseOut={onMouseOut} ... />`

Also, I think it'd be great to offer a tooltip render option upon hover.
Thank you for the clean abstractions!

**Comment by madox2** [comment]
Thanks for contribution! You can find these events in the latest version 2.1.0.
I have also added an option to pass custom props to a tag - you can use it to show title.
Take a look at this example: [examples/tag-props.js](https://github.com/madox2/react-tagcloud/blob/master/examples/src/tag-props.js)
