### ISSUE TITLE
Getting warning: React does not recognize the `containerComponent` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `containercomponent` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

### ISSUE THREAD

**Issue by DercilioFontes** [madox2/react-tagcloud#30]
I can see in the library code the use of `const Container = props.containerComponent`, line 102, TagCloud.js.

React warnings about that:
https://reactjs.org/warnings/unknown-prop.html 

Any way to fix that warning?

**Comment by madox2** [comment]
Thanks for reporting, find it fixed in the latest version.

**Comment by DercilioFontes** [comment]
@madox2, Thanks.
