### ISSUE TITLE
Disabling automatic shuffle

### ISSUE THREAD

**Issue by kdanet** [madox2/react-tagcloud#40]
I really need a props parameter that allowed the internal mixing mechanism to be disabled.

Like this: 

```javascript
<TagCloud disableAutoShuffle={true} ...props />
```

I think this is a very important tweak, especially when you want to sort the items in the cloud in your own way and it's important to keep the order passed on

**Comment by madox2** [comment]
Doesn't `shuffle={false}` do the trick?

**Comment by kdanet** [comment]
Thank you!
I guess I didn't see that option, sorry.
