### ISSUE TITLE
NaN when min and max are same

### ISSUE THREAD

**Issue by johnsoncze** [madox2/react-tagcloud#5]
Hi,

when tags contains only tags with same count, calculation of tag size contains division by zero https://github.com/madox2/react-tagcloud/blob/master/lib/tag-cloud.js#L37

Would be nice to return maxSize when min and max are same.

**Comment by madox2** [comment]
Hi, thanks for reporting! Maybe the value between `minSize` and `maxSize` would be even better. Could you make a PR?

**Comment by johnsoncze** [comment]
What about something like `defaultSize` prop that will be used in this case. Or what about don't set size when `min` and `max` are same? I will make a PR, but before that I want to discuss it :) Thanks
