### ISSUE TITLE
Deprecated warnings for componentWillMount and componentWillReceiveProps

### ISSUE THREAD

**Issue by jdimmerman** [madox2/react-tagcloud#9]
Hey! componentWillMount and componentWillReceiveProps are both deprecated and are throwing console warnings upon use - https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html.

**Comment by madox2** [comment]
Thanks for opening issue. I am going to fix it in the next release (2.0.0).

**Comment by jdimmerman** [comment]
awesome, thanks @madox2!
